/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeetTheTeamRouteImport } from './routes/meet-the-team'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as MentorshipProgramRouteImport } from './routes/mentorship-program'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SocialScienceExcellenceRouteImport } from './routes/social-science-excellence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetTheTeamRoute = MeetTheTeamRouteImport.update({
  id: '/meet-the-team',
  path: '/meet-the-team',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipProgramRoute = MentorshipProgramRouteImport.update({
  id: '/mentorship-program',
  path: '/mentorship-program',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialScienceExcellenceRoute = SocialScienceExcellenceRouteImport.update({
  id: '/social-science-excellence',
  path: '/social-science-excellence',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meet-the-team': typeof MeetTheTeamRoute
  '/mentor': typeof MentorRoute
  '/mentorship-program': typeof MentorshipProgramRoute
  '/partners': typeof PartnersRoute
  '/signup': typeof SignupRoute
  '/social-science-excellence': typeof SocialScienceExcellenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meet-the-team': typeof MeetTheTeamRoute
  '/mentor': typeof MentorRoute
  '/mentorship-program': typeof MentorshipProgramRoute
  '/partners': typeof PartnersRoute
  '/signup': typeof SignupRoute
  '/social-science-excellence': typeof SocialScienceExcellenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meet-the-team': typeof MeetTheTeamRoute
  '/mentor': typeof MentorRoute
  '/mentorship-program': typeof MentorshipProgramRoute
  '/partners': typeof PartnersRoute
  '/signup': typeof SignupRoute
  '/social-science-excellence': typeof SocialScienceExcellenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/meet-the-team'
    | '/mentor'
    | '/mentorship-program'
    | '/partners'
    | '/signup'
    | '/social-science-excellence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/meet-the-team'
    | '/mentor'
    | '/mentorship-program'
    | '/partners'
    | '/signup'
    | '/social-science-excellence'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/meet-the-team'
    | '/mentor'
    | '/mentorship-program'
    | '/partners'
    | '/signup'
    | '/social-science-excellence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MeetTheTeamRoute: typeof MeetTheTeamRoute
  MentorRoute: typeof MentorRoute
  MentorshipProgramRoute: typeof MentorshipProgramRoute
  PartnersRoute: typeof PartnersRoute
  SignupRoute: typeof SignupRoute
  SocialScienceExcellenceRoute: typeof SocialScienceExcellenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-the-team': {
      id: '/meet-the-team'
      path: '/meet-the-team'
      fullPath: '/meet-the-team'
      preLoaderRoute: typeof MeetTheTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship-program': {
      id: '/mentorship-program'
      path: '/mentorship-program'
      fullPath: '/mentorship-program'
      preLoaderRoute: typeof MentorshipProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-science-excellence': {
      id: '/social-science-excellence'
      path: '/social-science-excellence'
      fullPath: '/social-science-excellence'
      preLoaderRoute: typeof SocialScienceExcellenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MeetTheTeamRoute: MeetTheTeamRoute,
  MentorRoute: MentorRoute,
  MentorshipProgramRoute: MentorshipProgramRoute,
  PartnersRoute: PartnersRoute,
  SignupRoute: SignupRoute,
  SocialScienceExcellenceRoute: SocialScienceExcellenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
